"""
Streamlit app base template for data-viz skill.
Replace all {placeholder} values before running.
Generated by ck:data-viz-workflow.
"""
import streamlit as st
import pandas as pd
from modules.data_loader import load_data
from modules.chart_factory import bar_chart, line_chart, scatter_chart, heatmap

# Page config — must be first Streamlit call
st.set_page_config(
    page_title="{project_name}",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("{project_name}")
st.markdown("**Industry:** {industry} | **Dataset:** {dataset_source}")

# ── Data Loading ──────────────────────────────────────────────────────────────
df = load_data("data/processed/clean_dataset.csv")

# ── Sidebar Filters ───────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Filters")
    st.markdown(f"**Rows loaded:** {len(df):,}")
    # {FILTER_PLACEHOLDERS}

# ── KPI Metrics ───────────────────────────────────────────────────────────────
st.subheader("Key Metrics")
kpi1, kpi2, kpi3 = st.columns(3)
# {KPI_PLACEHOLDERS}

st.divider()

# ── Charts ────────────────────────────────────────────────────────────────────
# {CHART_SECTIONS}

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption("Data source: {dataset_source} | Generated by ck:data-viz")
